export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  SPECIALISTE_EN_ENVIRONNEMENT_ET_SOCIAL = 'ROLE_SPECIALISTE_EN_ENVIRONNEMENT_ET_SOCIAL',
  MISSION_DE_CONTROLE = 'ROLE_MISSION_DE_CONTROLE',
  RESPONSABLE_HSE = 'ROLE_RESPONSABLE_HSE',
  OUVRIER = 'ROLE_OUVRIER',
  RIVERAIN = 'ROLE_RIVERAIN',
}
